const CASE_DATA = {
  granite: [
    {name:"時代洲廳", location:"台中南屯區", builder:"瑞助營造", imgs:["case_images/mg/mg_001.jpg","case_images/mg/mg_002.jpg"]},
    {name:"麗景三期", location:"台中后里", builder:"鑫富安居", imgs:["case_images/mg/mg_003.jpg","case_images/mg/mg_004.jpg"]},
    {name:"展裕中山段28戶住宅", location:"台中大甲", builder:"展意營造", imgs:["case_images/mg/mg_005.jpg","case_images/mg/mg_006.jpg"]},
    {name:"保成段住宅", location:"台中沙鹿", builder:"永乾建設", imgs:["case_images/mg/mg_007.jpg"]},
    {name:"秀泰影城", location:"台中站前", builder:"秀泰娛樂", imgs:["case_images/mg/mg_008.jpg","case_images/mg/mg_009.jpg"]},
    {name:"立彩璞御", location:"台中西區", builder:"立彩建設", imgs:["case_images/mg/mg_010.jpg"]},
    {name:"柯芬園六期", location:"台中西屯區", builder:"大展營造", imgs:["case_images/mg/mg_011.jpg","case_images/mg/mg_012.jpg"]},
    {name:"北安段住宅", location:"台南安南", builder:"定坤營造", imgs:["case_images/mg/mg_013.jpg","case_images/mg/mg_014.jpg"]},
    {name:"黃氏住宅", location:"台南安南", builder:"定坤營造", imgs:["case_images/mg/mg_015.jpg","case_images/mg/mg_016.jpg"]},
    {name:"玉井帝寶5期", location:"台南玉井", builder:"龍毅建設", imgs:["case_images/mg/mg_017.jpg","case_images/mg/mg_018.jpg"]},
    {name:"張文昌自宅", location:"嘉義大林", builder:"新林營造", imgs:["case_images/mg/mg_019.jpg","case_images/mg/mg_020.jpg"]},
    {name:"權威安徒森大樓", location:"嘉義東區", builder:"權威建設", imgs:["case_images/mg/mg_021.jpg","case_images/mg/mg_022.jpg"]},
    {name:"鉑崇天下（新古典透天）", location:"嘉義民雄", builder:"伍灃營造", imgs:["case_images/mg/mg_023.jpg","case_images/mg/mg_024.jpg"]},
    {name:"鉑崇天下（現代風公寓）", location:"嘉義民雄", builder:"伍灃營造", imgs:["case_images/mg/mg_025.jpg","case_images/mg/mg_026.jpg"]},
    {name:"千葉里31戶", location:"嘉義民雄", builder:"全翔營造", imgs:["case_images/mg/mg_027.jpg","case_images/mg/mg_028.jpg"]},
    {name:"宜蘭建設工程", location:"宜蘭市", builder:"豪盟營造", imgs:["case_images/mg/mg_029.jpg","case_images/mg/mg_030.jpg"]},
    {name:"世富慶2期", location:"宜蘭五結", builder:"楠朝建設", imgs:["case_images/mg/mg_031.jpg","case_images/mg/mg_032.jpg"]},
    {name:"宏江森活一期", location:"宜蘭冬山", builder:"宏江開發", imgs:["case_images/mg/mg_033.jpg","case_images/mg/mg_034.jpg"]},
    {name:"桂冠富域", location:"宜蘭市", builder:"桂冠開發", imgs:["case_images/mg/mg_035.jpg","case_images/mg/mg_036.jpg"]},
    {name:"東港關帝段", location:"屏東東港", builder:"佐相建設", imgs:["case_images/mg/mg_037.jpg","case_images/mg/mg_038.jpg"]},
    {name:"桓御邸", location:"彰化員林", builder:"欣春建設", imgs:["case_images/mg/mg_039.jpg","case_images/mg/mg_040.jpg"]},
    {name:"合嘉尖石山段二期", location:"新北鶯歌", builder:"合嘉建設", imgs:["case_images/mg/mg_041.jpg","case_images/mg/mg_042.jpg"]},
    {name:"關西法雲寺", location:"新竹關西", builder:"德宇營造", imgs:["case_images/mg/mg_043.jpg","case_images/mg/mg_044.jpg"]},
    {name:"港南艾茉爾婚宴會館", location:"新竹香山", builder:"港南建設", imgs:["case_images/mg/mg_045.jpg","case_images/mg/mg_046.jpg"]},
    {name:"苗栗市店鋪", location:"苗栗市", builder:"昭月建設", imgs:["case_images/mg/mg_047.jpg"]},
    {name:"龍頂段", location:"苗栗後龍", builder:"居盛建設", imgs:["case_images/mg/mg_048.jpg","case_images/mg/mg_049.jpg"]},
    {name:"頭份大化段", location:"苗栗頭份", builder:"喬喜建設", imgs:["case_images/mg/mg_050.jpg","case_images/mg/mg_051.jpg"]},
    {name:"朱丹灣", location:"雲林斗六", builder:"永聖建設", imgs:["case_images/mg/mg_052.jpg","case_images/mg/mg_053.jpg"]},
    {name:"中山東四戶外牆工程", location:"台南永康", builder:"蕎粔建築", imgs:["case_images/mg/mg_054.jpg","case_images/mg/mg_055.jpg"]},
    {name:"神岡托嬰中心", location:"台中神岡", builder:"崗瑞營造", imgs:["case_images/mg/mg_056.jpg","case_images/mg/mg_057.jpg"]},
  ],
  mineral: [
    {name:"外埔納骨塔", location:"台中外埔", builder:"全進營造", imgs:["case_images/mgs/mgs_001.jpg","case_images/mgs/mgs_002.jpg"]},
    {name:"謝鴻猷幼兒園圍牆", location:"台中大肚", builder:"大肚永勝", imgs:["case_images/mgs/mgs_003.jpg","case_images/mgs/mgs_004.jpg"]},
    {name:"好耆長照中心", location:"台中梧棲", builder:"連信營造", imgs:["case_images/mgs/mgs_005.jpg","case_images/mgs/mgs_006.jpg"]},
    {name:"綠活FIKA住宅", location:"台中清水", builder:"宇豐營造", imgs:["case_images/mgs/mgs_007.jpg","case_images/mgs/mgs_008.jpg"]},
    {name:"南鯤鯓代天府鯤瀛樓", location:"台南北門區", builder:"慶洋營造", imgs:["case_images/mgs/mgs_009.jpg","case_images/mgs/mgs_010.jpg","case_images/mgs/mgs_031.jpg"]},
    {name:"興雅硯", location:"嘉義西區", builder:"欣歐建設", imgs:["case_images/mgs/mgs_011.jpg","case_images/mgs/mgs_012.jpg"]},
    {name:"穎峰建設北關段", location:"宜蘭頭城", builder:"緯築科技", imgs:["case_images/mgs/mgs_013.jpg","case_images/mgs/mgs_014.jpg"]},
    {name:"袁公館", location:"彰化埔心", builder:"黋憻營造", imgs:["case_images/mgs/mgs_015.jpg","case_images/mgs/mgs_016.jpg"]},
    {name:"隆宏昌廠辦", location:"彰化芳苑", builder:"良益營造", imgs:["case_images/mgs/mgs_017.jpg","case_images/mgs/mgs_018.jpg"]},
    {name:"回家2・會所", location:"新竹北埔", builder:"極美建設", imgs:["case_images/mgs/mgs_019.jpg","case_images/mgs/mgs_020.jpg"]},
    {name:"回家3期", location:"新竹北埔", builder:"極美建設", imgs:["case_images/mgs/mgs_021.jpg","case_images/mgs/mgs_022.jpg"]},
    {name:"觀美建築會館", location:"新竹北埔", builder:"極美建設", imgs:["case_images/mgs/mgs_023.jpg","case_images/mgs/mgs_024.jpg"]},
    {name:"鄒秀華住宅", location:"桃園中壢", builder:"鈞茂營造", imgs:["case_images/mgs/mgs_025.jpg","case_images/mgs/mgs_026.jpg"]},
    {name:"兆品酒店", location:"苗栗竹南", builder:"GRC工法", imgs:["case_images/mgs/mgs_027.jpg","case_images/mgs/mgs_028.jpg"]},
    {name:"德鴻臻美11期", location:"雲林斗南", builder:"德鴻開發", imgs:["case_images/mgs/mgs_029.jpg","case_images/mgs/mgs_030.jpg"]},
    {name:"台塑大金廠警衛室", location:"高雄大寮", builder:"上欣營造", imgs:["case_images/mgs/mgs_032.jpg","case_images/mgs/mgs_033.jpg"]},
  ],
};