const CASE_DATA = {
  granite: [
    {name:"住宅外牆工程", location:"台中南屯區", builder:"", imgs:["case_images/mg/mg_001.jpg","case_images/mg/mg_002.jpg"]},
    {name:"住宅外牆工程", location:"台中后里", builder:"", imgs:["case_images/mg/mg_003.jpg","case_images/mg/mg_004.jpg"]},
    {name:"住宅外牆工程", location:"台中大甲", builder:"", imgs:["case_images/mg/mg_005.jpg","case_images/mg/mg_006.jpg"]},
    {name:"住宅外牆工程", location:"台中沙鹿", builder:"", imgs:["case_images/mg/mg_007.jpg"]},
    {name:"秀泰影城", location:"台中站前秀泰影城(麥金005", builder:"", imgs:["case_images/mg/mg_008.jpg","case_images/mg/mg_009.jpg"]},
    {name:"住宅外牆工程", location:"台中西區", builder:"", imgs:["case_images/mg/mg_010.jpg"]},
    {name:"住宅外牆工程", location:"台中西屯區", builder:"", imgs:["case_images/mg/mg_011.jpg","case_images/mg/mg_012.jpg"]},
    {name:"住宅外牆工程", location:"台南安南", builder:"", imgs:["case_images/mg/mg_013.jpg","case_images/mg/mg_014.jpg"]},
    {name:"住宅外牆工程", location:"台南安南", builder:"", imgs:["case_images/mg/mg_015.jpg","case_images/mg/mg_016.jpg"]},
    {name:"住宅外牆工程", location:"台南永康", builder:"", imgs:["case_images/mg/mg_017.jpg"]},
    {name:"住宅外牆工程", location:"台南玉井", builder:"", imgs:["case_images/mg/mg_018.jpg","case_images/mg/mg_019.jpg"]},
    {name:"住宅外牆工程", location:"嘉義大林", builder:"", imgs:["case_images/mg/mg_020.jpg","case_images/mg/mg_021.jpg"]},
    {name:"住宅外牆工程", location:"嘉義東區", builder:"", imgs:["case_images/mg/mg_022.jpg","case_images/mg/mg_023.jpg"]},
    {name:"住宅外牆工程", location:"嘉義民雄", builder:"", imgs:["case_images/mg/mg_024.jpg","case_images/mg/mg_025.jpg"]},
    {name:"住宅外牆工程", location:"嘉義民雄", builder:"", imgs:["case_images/mg/mg_026.jpg","case_images/mg/mg_027.jpg"]},
    {name:"住宅外牆工程", location:"嘉義民雄", builder:"", imgs:["case_images/mg/mg_028.jpg","case_images/mg/mg_029.jpg"]},
    {name:"住宅外牆工程", location:"宜蘭", builder:"", imgs:["case_images/mg/mg_030.jpg","case_images/mg/mg_031.jpg"]},
    {name:"住宅外牆工程", location:"宜蘭五結", builder:"", imgs:["case_images/mg/mg_032.jpg","case_images/mg/mg_033.jpg"]},
    {name:"住宅外牆工程", location:"宜蘭冬山", builder:"", imgs:["case_images/mg/mg_034.jpg","case_images/mg/mg_035.jpg"]},
    {name:"住宅外牆工程", location:"宜蘭市", builder:"", imgs:["case_images/mg/mg_036.jpg","case_images/mg/mg_037.jpg"]},
    {name:"住宅外牆工程", location:"屏東東港", builder:"", imgs:["case_images/mg/mg_038.jpg","case_images/mg/mg_039.jpg"]},
    {name:"住宅外牆工程", location:"彰化員林", builder:"", imgs:["case_images/mg/mg_040.jpg","case_images/mg/mg_041.jpg"]},
    {name:"住宅外牆工程", location:"新北鶯歌", builder:"", imgs:["case_images/mg/mg_042.jpg","case_images/mg/mg_043.jpg"]},
    {name:"關西法雲寺", location:"新竹關西", builder:"", imgs:["case_images/mg/mg_044.jpg","case_images/mg/mg_045.jpg"]},
    {name:"港南艾茉爾婚宴會館", location:"新竹香山", builder:"", imgs:["case_images/mg/mg_046.jpg","case_images/mg/mg_047.jpg"]},
    {name:"商業大樓外牆工程", location:"苗栗市", builder:"", imgs:["case_images/mg/mg_048.jpg"]},
    {name:"住宅外牆工程", location:"苗栗後龍", builder:"", imgs:["case_images/mg/mg_049.jpg","case_images/mg/mg_050.jpg"]},
    {name:"住宅外牆工程", location:"苗栗頭份", builder:"", imgs:["case_images/mg/mg_051.jpg","case_images/mg/mg_052.jpg"]},
    {name:"住宅外牆工程", location:"雲林斗六", builder:"", imgs:["case_images/mg/mg_053.jpg","case_images/mg/mg_054.jpg"]},
    {name:"教育機構外牆工程", location:"台中神岡", builder:"", imgs:["case_images/mg/mg_055.jpg","case_images/mg/mg_056.jpg"]},
  ],
  mineral: [
    {name:"納骨塔外牆工程", location:"台中外埔", builder:"", imgs:["case_images/mgs/mgs_001.jpg","case_images/mgs/mgs_002.jpg"]},
    {name:"教育機構外牆工程", location:"台中大肚", builder:"", imgs:["case_images/mgs/mgs_003.jpg","case_images/mgs/mgs_004.jpg"]},
    {name:"住宅外牆工程", location:"台中梧棲", builder:"", imgs:["case_images/mgs/mgs_005.jpg","case_images/mgs/mgs_006.jpg"]},
    {name:"住宅外牆工程", location:"台中清水", builder:"", imgs:["case_images/mgs/mgs_007.jpg","case_images/mgs/mgs_008.jpg"]},
    {name:"南鯤鯓代天府", location:"台南北門區", builder:"", imgs:["case_images/mgs/mgs_009.jpg"]},
    {name:"南鯤鯓代天府", location:"台南北門區", builder:"", imgs:["case_images/mgs/mgs_010.jpg","case_images/mgs/mgs_011.jpg"]},
    {name:"住宅外牆工程", location:"嘉義西區", builder:"", imgs:["case_images/mgs/mgs_012.jpg","case_images/mgs/mgs_013.jpg"]},
    {name:"住宅外牆工程", location:"宜蘭頭城", builder:"", imgs:["case_images/mgs/mgs_014.jpg","case_images/mgs/mgs_015.jpg"]},
    {name:"住宅外牆工程", location:"彰化埔心", builder:"", imgs:["case_images/mgs/mgs_016.jpg","case_images/mgs/mgs_017.jpg"]},
    {name:"商業大樓外牆工程", location:"彰化芳苑", builder:"", imgs:["case_images/mgs/mgs_018.jpg","case_images/mgs/mgs_019.jpg"]},
    {name:"住宅外牆工程", location:"新竹北埔", builder:"", imgs:["case_images/mgs/mgs_020.jpg","case_images/mgs/mgs_021.jpg"]},
    {name:"住宅外牆工程", location:"新竹北埔", builder:"", imgs:["case_images/mgs/mgs_022.jpg","case_images/mgs/mgs_023.jpg"]},
    {name:"商業大樓外牆工程", location:"新竹北埔", builder:"", imgs:["case_images/mgs/mgs_024.jpg","case_images/mgs/mgs_025.jpg"]},
    {name:"住宅外牆工程", location:"桃園中壢", builder:"", imgs:["case_images/mgs/mgs_026.jpg","case_images/mgs/mgs_027.jpg"]},
    {name:"兆品酒店", location:"苗栗竹南", builder:"", imgs:["case_images/mgs/mgs_028.jpg","case_images/mgs/mgs_029.jpg"]},
    {name:"住宅外牆工程", location:"雲林斗南", builder:"", imgs:["case_images/mgs/mgs_030.jpg","case_images/mgs/mgs_031.jpg"]},
    {name:"商業大樓外牆工程", location:"高雄大寮", builder:"", imgs:["case_images/mgs/mgs_032.jpg","case_images/mgs/mgs_033.jpg"]},
  ],
};