const CASE_DATA = {
  granite: [
    {name:"時代洲廳(GRC.麥金", location:"台中南屯區", builder:"瑞助營造", imgs:["case_images/mg/mg_001.jpg","case_images/mg/mg_002.jpg"]},
    {name:"麗景三期(GRC.麥金016", location:"台中后里", builder:"鑫富安居", imgs:["case_images/mg/mg_003.jpg","case_images/mg/mg_004.jpg"]},
    {name:"住宅外牆工程", location:"台中大甲", builder:"展意營造", imgs:["case_images/mg/mg_005.jpg","case_images/mg/mg_006.jpg"]},
    {name:"保成段(麥金", location:"台中沙鹿", builder:"永乾建設", imgs:["case_images/mg/mg_007.jpg"]},
    {name:"台中站前秀泰影城(麥金005", location:"台中站前秀泰影城(麥金005", builder:"", imgs:["case_images/mg/mg_008.jpg","case_images/mg/mg_009.jpg"]},
    {name:"立彩璞御(GRC.麥金", location:"台中西區", builder:"立彩建設", imgs:["case_images/mg/mg_010.jpg"]},
    {name:"柯芬園六期(GRC.麥金", location:"台中西屯區", builder:"大展營造", imgs:["case_images/mg/mg_011.jpg","case_images/mg/mg_012.jpg"]},
    {name:"北安段(麥金.S25滴水條", location:"台南安南", builder:"定坤營造", imgs:["case_images/mg/mg_013.jpg","case_images/mg/mg_014.jpg"]},
    {name:"住宅外牆工程", location:"台南安南", builder:"定坤營造", imgs:["case_images/mg/mg_015.jpg","case_images/mg/mg_016.jpg"]},
    {name:"中山東67.69.71.73號四戶外牆塗料工程(麥金.S25滴水條", location:"台南永康", builder:"蕎粔建築開發", imgs:["case_images/mg/mg_017.jpg"]},
    {name:"玉井帝寶5期(麥金.GRC", location:"台南玉井", builder:"龍毅建設", imgs:["case_images/mg/mg_018.jpg","case_images/mg/mg_019.jpg"]},
    {name:"住宅外牆工程", location:"嘉義大林", builder:"新林營造", imgs:["case_images/mg/mg_020.jpg","case_images/mg/mg_021.jpg"]},
    {name:"權威安徒森大樓外牆塗料工程(麥金", location:"嘉義東區", builder:"權威建設", imgs:["case_images/mg/mg_022.jpg","case_images/mg/mg_023.jpg"]},
    {name:"鉑崇天下匯秀新古典透天(麥金.ㄇ型滴水條GRC", location:"嘉義民雄", builder:"伍灃營造", imgs:["case_images/mg/mg_024.jpg","case_images/mg/mg_025.jpg"]},
    {name:"鉑崇天下匯秀現代風公寓(麥金.ㄇ型滴水條", location:"嘉義民雄", builder:"伍灃營造", imgs:["case_images/mg/mg_026.jpg","case_images/mg/mg_027.jpg"]},
    {name:"千葉里31戶(麥金", location:"嘉義民雄", builder:"全翔營造", imgs:["case_images/mg/mg_028.jpg","case_images/mg/mg_029.jpg"]},
    {name:"豪盟營造", location:"宜蘭", builder:"", imgs:["case_images/mg/mg_030.jpg","case_images/mg/mg_031.jpg"]},
    {name:"世富慶2期(麥金", location:"宜蘭五結", builder:"楠朝建設", imgs:["case_images/mg/mg_032.jpg","case_images/mg/mg_033.jpg"]},
    {name:"宏江森活一期(麥金", location:"宜蘭冬山", builder:"宏江開發", imgs:["case_images/mg/mg_034.jpg","case_images/mg/mg_035.jpg"]},
    {name:"桂冠富域艮門二段(麥金、ㄇ型滴水條", location:"宜蘭市", builder:"桂冠開發", imgs:["case_images/mg/mg_036.jpg","case_images/mg/mg_037.jpg"]},
    {name:"0901 佐相建設-東港關帝段一樓追加", location:"屏東東港", builder:"", imgs:["case_images/mg/mg_038.jpg","case_images/mg/mg_039.jpg"]},
    {name:"欣春建設【桓御邸】(雅彈.麥金", location:"彰化員林", builder:"士林開發案件", imgs:["case_images/mg/mg_040.jpg","case_images/mg/mg_041.jpg"]},
    {name:"合嘉尖石山段二期(麥金", location:"新北鶯歌", builder:"合嘉建設", imgs:["case_images/mg/mg_042.jpg","case_images/mg/mg_043.jpg"]},
    {name:"關西法雲寺(GRC.麥金", location:"新竹關西", builder:"德宇營造", imgs:["case_images/mg/mg_044.jpg","case_images/mg/mg_045.jpg"]},
    {name:"港南艾茉爾婚宴會館(麥金崗、GRC", location:"新竹香山", builder:"", imgs:["case_images/mg/mg_046.jpg","case_images/mg/mg_047.jpg"]},
    {name:"苗栗市店鋪三戶(麥金、ㄇ型滴水條", location:"苗栗市", builder:"昭月建設", imgs:["case_images/mg/mg_048.jpg"]},
    {name:"龍頂段(GRC.麥金", location:"苗栗後龍", builder:"居盛建設", imgs:["case_images/mg/mg_049.jpg","case_images/mg/mg_050.jpg"]},
    {name:"0702、T115-0102 喬喜建設-頭份大化段(GRC.麥金.S25", location:"苗栗頭份", builder:"", imgs:["case_images/mg/mg_051.jpg","case_images/mg/mg_052.jpg"]},
    {name:"朱丹灣(GRC.崗石", location:"雲林斗六", builder:"永聖建設", imgs:["case_images/mg/mg_053.jpg","case_images/mg/mg_054.jpg"]},
    {name:"神岡托嬰中心", location:"台中神岡", builder:"崗瑞營造", imgs:["case_images/mg/mg_055.jpg","case_images/mg/mg_056.jpg"]},
  ],
  mineral: [
    {name:"納骨塔外牆工程", location:"台中外埔", builder:"全進營造", imgs:["case_images/mgs/mgs_001.jpg","case_images/mgs/mgs_002.jpg"]},
    {name:"幼兒園圍牆工程", location:"台中大肚", builder:"大肚永勝", imgs:["case_images/mgs/mgs_003.jpg","case_images/mgs/mgs_004.jpg"]},
    {name:"好耆長照中心(單彩、ㄇ型滴水條", location:"台中梧棲", builder:"連信營造", imgs:["case_images/mgs/mgs_005.jpg","case_images/mgs/mgs_006.jpg"]},
    {name:"住宅外牆工程", location:"台中清水", builder:"宇豐營造", imgs:["case_images/mgs/mgs_007.jpg","case_images/mgs/mgs_008.jpg"]},
    {name:"南鯤鯓代天府鯤瀛樓1(修掉鷹架", location:"台南北門區", builder:"慶洋營造", imgs:["case_images/mgs/mgs_009.jpg"]},
    {name:"南鯤鯓代天府鯤瀛樓(質感塗料", location:"台南北門區", builder:"慶洋營造", imgs:["case_images/mgs/mgs_010.jpg","case_images/mgs/mgs_011.jpg"]},
    {name:"興雅硯外牆塗料工程(耐候單彩", location:"嘉義西區", builder:"欣歐建設", imgs:["case_images/mgs/mgs_012.jpg","case_images/mgs/mgs_013.jpg"]},
    {name:"穎峰建設北關段(耐候單彩.ㄇ型", location:"宜蘭頭城", builder:"緯築科技(玳偉)", imgs:["case_images/mgs/mgs_014.jpg","case_images/mgs/mgs_015.jpg"]},
    {name:"住宅外牆工程", location:"彰化埔心", builder:"黋憻營造", imgs:["case_images/mgs/mgs_016.jpg","case_images/mgs/mgs_017.jpg"]},
    {name:"隆宏昌興業芳苑廠辦(釉彩花崗石漆", location:"彰化芳苑", builder:"良益營造", imgs:["case_images/mgs/mgs_018.jpg","case_images/mgs/mgs_019.jpg"]},
    {name:"回家2、會所(麥金耐候單彩、ㄇ型滴水條", location:"新竹北埔", builder:"極美建設", imgs:["case_images/mgs/mgs_020.jpg","case_images/mgs/mgs_021.jpg"]},
    {name:"回家3(麥金耐候單彩、ㄇ型滴水條", location:"新竹北埔", builder:"極美建設", imgs:["case_images/mgs/mgs_022.jpg","case_images/mgs/mgs_023.jpg"]},
    {name:"觀美建築會館.ㄇ型滴水條", location:"新竹北埔", builder:"極美建設", imgs:["case_images/mgs/mgs_024.jpg","case_images/mgs/mgs_025.jpg"]},
    {name:"住宅外牆工程", location:"桃園中壢", builder:"鈞茂營造", imgs:["case_images/mgs/mgs_026.jpg","case_images/mgs/mgs_027.jpg"]},
    {name:"兆品酒店(GRC.麥金", location:"苗栗竹南", builder:"", imgs:["case_images/mgs/mgs_028.jpg","case_images/mgs/mgs_029.jpg"]},
    {name:"德鴻臻美11期(佩能漆S25", location:"雲林斗南", builder:"德鴻開發", imgs:["case_images/mgs/mgs_030.jpg","case_images/mgs/mgs_031.jpg"]},
    {name:"廠區工程", location:"高雄大寮", builder:"上欣營造", imgs:["case_images/mgs/mgs_032.jpg","case_images/mgs/mgs_033.jpg"]},
  ],
};